name: CD

on:
  push:
    branches: [ master ]

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install essentials
      run: |
        sudo apt-get update -y
        sudo apt-get install software-properties-common -y
        sudo apt-get install unzip -y
        sudo apt-get install git -y
    
    - name: Install Packer
      run: |
        export VER="1.5.5"
        wget https://releases.hashicorp.com/packer/${VER}/packer_${VER}_linux_amd64.zip
        sudo unzip packer_${VER}_linux_amd64.zip
        sudo mv packer /usr/local/bin
     
    - name: Install Ansible
      run: |
        sudo apt-add-repository --yes ppa:ansible/ansible
        sudo apt-get install ansible -y
        ansible --version

    - name: Install Ansible role
      run:  |
        sudo ansible-galaxy install anxs.postgresql -r ansible/install_roles.yml --force -vvv
        ansible-galaxy list anxs.postgresql
        
    - name: Build Digital Ocean Snapshot
      run: |
        export REGION=sgp1
        export SNAPSHOT_REGIONS="nyc1,nyc3,ams3,sfo2,sfo3,sgp1,lon1,fra1,tor1"
        sudo packer build \
        -var "do_token=${{ secrets.DO_TOKEN }}" \
        -var "region=$REGION" \
        -var "snapshot_regions=$SNAPSHOT_REGIONS" \
        digitalOcean.json

    # - name: Build Digital Ocean Snapshot for Marketplace
    #   run: |
    #     export REGION=sgp1
    #     export IMAGE_NAME="supabase-supabasepostgres-18-04"
    #     export ARGS="--tags,update"
    #     sudo packer build \
    #     -var "do_token=${{ secrets.DO_TOKEN }}" \
    #     -var "region=$REGION" \
    #     -var "image_name=$IMAGE_NAME" \
    #     -var "ansible_arguments=$ARGS" \
    #     digitalOcean.json
