language: node_js
matrix:
  include:
    - node_js: "10"
      before_install:
        - "npm install -g npm@latest"
    - node_js: "8"
      before_install:
        - "npm install -g npm@latest"
    - node_js: "6"
      before_install:
        - "npm install -g npm@latest"
    - node_js: "4"
      before_install:
        - "npm install -g npm@5"
script: "npm test"
sudo: false
notifications:
    slack: npm-inc:kRqQjto7YbINqHPb1X6nS3g8
