---
- name: symlink release
  file: >
    src={{ deploy_release_dir }}
    dest={{ deploy_application_home }}/current
    state=link
    owner={{ ansible_ssh_user }}
    group={{ ansible_ssh_user }}
    force=yes
