- name: copy pgbouncer.ini
  sudo: true
  notify: restart pgbouncer
  template: >
    src=pgbouncer-bouncer.ini.j2
    dest=/etc/pgbouncer/pgbouncer.ini
    owner=postgres
    group=postgres
    mode=0644

- name: enable pgbouner
  sudo: true
  notify: restart pgbouncer
  lineinfile: >
    dest=/etc/default/pgbouncer
    line="START=1"
    regexp='^START.*$'

- name: copy users list
  sudo: true
  notify: restart pgbouncer
  copy: >
    src=pgbouncer.users
    dest=/etc/pgbouncer/pgbouncer.users
    owner=postgres
    group=postgres
    mode=0644
