- hosts: all
  become: yes

  pre_tasks:
    - import_tasks: tasks/setup-system.yml
  
  vars_files:
    - ./vars.yml
  
  roles:
    - role: anxs.postgresql

  tasks:
    - name: Install non-Postgres extensions
      import_tasks: tasks/setup-misc.yml

    - name: Install Postgres extensions
      import_tasks: tasks/setup-extensions.yml

    - name: Adjust APT update intervals
      copy: 
        src: files/apt_periodic
        dest: /etc/apt/apt.conf.d/10periodic

    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Allow connections to postgreSQL (5432)
      ufw:
        rule: allow
        port: '5432'

    - name: UFW - Deny all other incoming traffix by default
      ufw: 
        state: enabled
        policy: deny
        direction: incoming