postgresql_version: 12
postgresql_wal_level: "logical"
postgresql_max_wal_senders: 10
postgresql_max_replication_slots: 5
postgresql_row_security: on
postgresql_listen_addresses:
  - "*"

postgresql_ext_install_contrib: yes
postgresql_ext_install_dev_headers: yes

# Warning: Make sure the postgresql & postgis versions are compatible with one another
postgresql_ext_postgis_version: 3

postgresql_shared_preload_libraries: [pg_stat_statements, pgaudit, plpgsql, plpgsql_check ]

postgresql_pg_hba_custom:
  - {type: "host", database: "all", user: "all", address: "0.0.0.0/0", method: "md5" }

pgtap_release: "1.1.0"
pgtap_release_checksum: sha1:cca57708e723de18735a723b774577dc52f6f31e

pgaudit_release: "1.4.0"
pgaudit_release_checksum: sha1:ea085fbf227b5c461331ab33b99579f37db299a6

pgsql_http_release: "1.3.1"
pgsql_http_release_checksum: sha1:816a3fff53e05301b176cf0696799fc5a00f54e8

plpgsql_check_release: "1.11.0"
plpgsql_check_release_checksum: sha1:395313b6ef9c10c4fc182817d6f0040b171147b8

pljava_release: "1_5_5"
pljava_release_checksum: sha1:5277433030fdeed8528c7c0154163b54aedbd842

postgresql_log_destination: "csvlog"
postgresql_logging_collector: on
postgresql_log_filename: "postgresql.log"
postgresql_log_rotation_age: 0
postgresql_log_rotation_size: 0

wal_g_release: "0.2.15"
wal_g_release_checksum: sha1:e82d405121e0ccc322a323b9824e60c102b14004