---
  - name: restart pgbouncer
    sudo: true
    command: pgrep pgbouncer | xargs kill -9; service pgbouncer start

  - name: restart repmgrd
    sudo: true
    service: name=repmgrd state=restarted
