baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
defaultContentLanguage = "en"
paginate = 2
enableRobotsTXT = true

[params]
  maxPaginatorCount = 2

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
