[en]
  title = "Filips Blogs"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[fr]
  title = "Filipove Blogy"
  languageName = "Slovak"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/fr"
