[[main]]
  identifier = "blogs"
  name = "Blogs"
  url = "blogs"
  weight = 10

[[main]]
  identifier = "faq"
  name = "Faq"
  url = "faq"
  weight = 9

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 8
